### ISSUE TITLE
plpython2« zugreifen

### ISSUE THREAD

**Issue by angelablancovogt79** [bstroebl/xplanPostGIS#1]
Vielen Dank für die Schema.
Ich bekomme diese Fehlermeldung "ERROR:  FEHLER:  konnte nicht auf Datei »$libdir/plpython2« zugreifen: No such file or directory". Ich habe Python27 auf dem Rechner. Was soll  ich machen?

**Comment by bstroebl** [comment]
war mit 0721fa7e864d8ca745e86be8db80754fb94f4d77 bereits gelöst und auf eine PostgreSQL-eigene Extension umgestellt, ich hatte es nur noch nicht in master gemergt
