### ISSUE TITLE
Funktion XP_Basisobjekte.

### ISSUE THREAD

**Issue by angelablancovogt79** [bstroebl/xplanPostGIS#2]
Viele Dank für die Rückmeldung.
ich bin neue mit dem Thema. 
Gerade versuche die *QGIS.sql aufführen und bekomme diese Fehlermeldung. 
ERROR:  FEHLER:  Funktion XP_Basisobjekte.ensure_sequence(unknown, unknown, unknown) existiert nicht
LINE 170: SELECT "XP_Basisobjekte".ensure_sequence('QGIS', 'layer', 'i...
                 ^
HINT:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufüg

Könnten Sie mich bitte unterstützen, wie ich den Fehler beheben kann?
Vielen Dank

**Comment by bstroebl** [comment]
Sie müssen die SQL-Skripte in der richtigen angegebenen Reihenfolge ausführen, siehe README bzw. createdb.sh

**Comment by angelablancovogt79** [comment]
Sorry, dass ich so viel fragen und danke für die Rückmeldungen.
Jetzt habe ich diesen Fehler Meldung:
ERROR:  FEHLER:  Schema »XP_Basisobjekte« existiert nicht

**Comment by bstroebl** [comment]
Sie müssen als allererstes `XP_Basisschema.sql` ausführen

**Comment by angelablancovogt79** [comment]
Ja genau, ich führe die XP_Basisschema.sql auf. Da bekomme ich den Fehler: ERROR:  FEHLER:  Schema »XP_Basisobjekte« existiert bereits

**Comment by bstroebl** [comment]
Vorher schrieben Sie 

> ERROR: FEHLER: Schema »XP_Basisobjekte« existiert nicht

Wenn es jetzt bereits existiert müssen Sie es wieder löschen oder löschen Sie einfach die gesamte Datenbank und fangen Sie nochmal von vorne an.

**Comment by bstroebl** [comment]
Wenn Sie die branch `master` ausgecheckt haben, dürfte das eigentlich nicht passieren.
An welcher Stelle (Zeile) wird denn der Fehler geworfen?

**Comment by angelablancovogt79** [comment]
Es sieht so aus, dass der Fehler hier sich befindet: 
87     CREATE OR REPLACE FUNCTION "XP_Basisobjekte".create_uuid() 

ich habe angepasst, wie Sie hier geschrieben haben: https://github.com/bstroebl/xplanPostGIS/commit/0721fa7e864d8ca745e86be8db80754fb94f4d77
kann es sein, dass ich etwas verpassen?
Vielen Dank

**Comment by bstroebl** [comment]
Bitte nutzen Sie ausschließlich die SQL-Dateien aus der Branch `master`, Sie müssen dort nichts mehr anpassen. Der Fehler kann dort nicht auftreten, denn die Funktion wird mit dem Befehl ja angelegt. 
Welche PostgreSQL-Version benutzen Sie?

**Comment by angelablancovogt79** [comment]
Wunderbar Herr Ströbl. Es hat geklappt. Wir müssen nun uns in das Thema einarbeiten. Wir wünschen einen sonnigen Tag aus Leinfelden-Echterdingen. Ich habe Postgres 10.3 auf meinen Rechner.

**Comment by bstroebl** [comment]
Puhh :-)
Ich habe letzte Woche auf dem QGIS-Anwendertreffen einen Workshop angeboten. Die Unterlagen dazu finden Sie [hier](https://github.com/bstroebl/xplanplugin/tree/master/workshop)
