### ISSUE TITLE
Error in layer_styles_QGIS

### ISSUE THREAD

**Issue by Michael700421** [bstroebl/xplanPostGIS#4]
Hallo Herr Ströbel,

ich versuche mich gerade in dem Thema Postgres und Xplanung einzuarbeiten. 

Unter Postgres 9.6 (Win 10) konnte ich die Fachschemata (Master) erfolgreich anlegen. Um mit dem QGIS Plugin zu arbeiten habe ich die *QGIS.sgl eingelesen. 

Gescheitert bin ich an dem layer_styles_QGIS.sql mit folgender Fehlermeldung:
_ERROR: FEHLER: Syntaxfehler bei »P« LINE 53023: ...itScale="0,0,0,0,0,0" fontSize="8.25" fieldName="'P &amp; R'...**_

Haben Sie einen Tipp.

Freundliche Grüße

**Comment by tschuettenberg** [comment]
Hallo!
Es gibt ein paar kleine Fehler im Layerstil zu BP_Verkehr.BP_VerkehrsFlaecheBesondererZweckbestimmungFlaeche.
Das Problem wird hier behandelt: https://github.com/bstroebl/xplanplugin/issues/4
Beste Grüße

**Comment by bstroebl** [comment]
Bitte wieder öffnen, falls das Problem durch den gegebenen Hinweis nicht gelöst wurde.
