### ISSUE TITLE
Fehlendes Feld "sonstZiel" in "FP_Naturschutz"."FP_AusgleichsFlaeche"

### ISSUE THREAD

**Issue by swen100** [bstroebl/xplanPostGIS#7]
Laut Objektartenkatalog besitzt das FeatureType "**xplan:FP_AusgleichsFlaeche**" das Attribut "xplan:sonstZiel" - in der Tabelle fehlt hierfür allerdings die entsprechende Spalte.

*xplan:sonstZiel CharacterString [0..1] Textlich formuliertes Ziel, wenn das Attribut ziel den Wert 9999 (Sonstiges) hat.*

**Comment by bstroebl** [comment]
das Feld ist mit XPlan 5 reingekommen und mir offensichtlich durch die Lappen gegangen. Ich würde vermuten, dass da noch mehr schlummert, danke für's Finden
